steps:
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: yarn
    args: ['install', '--production']
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: yarn
    args: ['create-app-yaml']
    env:
      - 'SECRET_TOKEN=${_SECRET_TOKEN}'
      - 'DB_HOST=${_DB_HOST}'
      - 'DB_USER=${_DB_USER}'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'DB_DATABASE=${_DB_DATABASE}'
      - 'DB_INSTANCE_CONNECTION_NAME=${_DB_INSTANCE_CONNECTION_NAME}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
